### ISSUE TITLE
Listen Angle should be 180? 

### ISSUE THREAD

**Issue by namrog84** [Tactical-Starbase/TPS#1]
In the diagram it shows listen angle as 45. Shouldn't they be 180 (So they are omnidirectional)?

Or do the receivers need to be positioned exactly as shown with their relative position/directions)?

Thanks!

**Comment by zeplintwo** [comment]
No the screen shot was taken before configuration of the unit. They are sorta omnidirectional. They can be used as a RDF but when in 180 mode they are using both postive and negative looking directions.

**Comment by namrog84** [comment]
If they were taken before the configuration of the unit, shouldn't they have had default names for everything then?

edit:
oh it looks like you've updated the photos. So the answer was yes.  Thanks!
